### ISSUE TITLE
Cole - integrate local code into new repo

### ISSUE THREAD

**Issue by mjstealey** [SciDAS/slurm-in-docker#12]
@cbmckni - to integrate code from local machine into repo

**Comment by cbmckni** [comment]
My local code is already integrated into the "cbmckni" branch. Do I need to do anything else?

**Comment by mjstealey** [comment]
@cbmckni - create a pull request and ensure there are no conflicts with the master branch.

Once a PR is in place it's easier for me to review the contents and make suggestions.
