### ISSUE TITLE
slurm.conf - allow user to pass in their own file

### ISSUE THREAD

**Issue by mjstealey** [SciDAS/slurm-in-docker#13]
To allow users to run on their own infrastructure they want to provide more custom settings than what the autogenerated slurm.conf file provides

**Comment by cbmckni** [comment]
Support has been added in branch "13-pass-conf", but does not verify configuration is correct.

**Comment by mjstealey** [comment]
@cbmckni - will have a look at the branch and report back what I find.

**Comment by mjstealey** [comment]
updates merged, closing
